Array Properties

In [1]:
'''Create this array:
arr = np.array([[10, 20, 30],[40, 50, 60]])
Then answer:
Q1. Find its number of dimensions.'''
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print()
print(arr.ndim)

[[10 20 30]
 [40 50 60]]

2


In [2]:
#2.find its shape
print(arr.shape)

(2, 3)


In [3]:
#3Find the total number of elements in arr.
print(arr.size)

6


In [4]:
#4 Find the data type of arr.
print(arr.dtype)

int64


In [5]:
#Q5. Find the size of each element in bytes.
print(arr.itemsize)

8


In [6]:
#Q6. Create a 3D array and find its:dimensions,shape,size,data type
arr1=np.array([[[7,8,9],[2,5,6]]])
print(arr1)
print(arr1.ndim)              #dimensions of array
print()
print(arr1.shape)              #shape of array
print()
print(arr1.size)            #size of array
print(arr1.dtype)           #type of array

[[[7 8 9]
  [2 5 6]]]
3

(1, 2, 3)

6
int64


In [7]:
#Array Operations

In [8]:
'''Use:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])'''
#Q1. Add a and b.
import numpy as np
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])
varadd=np.add(a,b)
print(varadd)

[11 22 33 44 55]


In [9]:
#Q2. Subtract b from a.
sub=np.subtract(a,b)
print(sub)

[ 9 18 27 36 45]


In [10]:
#Q3. Multiply the arrays.
multi=np.multiply(a,b)
print(multi)

[ 10  40  90 160 250]


In [11]:
#Q4. Divide a by b.
div=np.divide(a,b)
print(div)

[10. 10. 10. 10. 10.]


In [12]:
#Q5. Find a².
a = np.array([10, 20, 30, 40, 50])
print(a**2)

[ 100  400  900 1600 2500]


In [13]:
#Q6. Add 10 to every element of a.
a = np.array([10, 20, 30, 40, 50])
print(a+10)

[20 30 40 50 60]


In [14]:
#Q7. Multiply every element of a by 3.
a = np.array([10, 20, 30, 40, 50])
print(a*3)

[ 30  60  90 120 150]


In [15]:
#Q8. Compare a > 25.
a = np.array([10, 20, 30, 40, 50])
print(a > 25)

[False False  True  True  True]


In [16]:
#Q9. Find which elements of a are equal to 30.
a = np.array([10, 20, 30, 40, 50])
print(a[a == 30])

[30]


In [17]:
#Q10. Calculate the percentage increase between corresponding values of a and b
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])
percentage = ((a - b) / b) * 100
print(percentage)

[900. 900. 900. 900. 900.]
