In [1]:
#Broadcasting

In [3]:
#Q1. Add 10 to every element:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr+10)

[11 12 13 14 15]


In [4]:
#Q2. Multiply every element by 5.
arr = np.array([1, 2, 3, 4, 5])
print(arr*5)

[ 5 10 15 20 25]


In [5]:
#Q3. Add:
a = np.array([10, 20, 30])
b = 5
print(a+b)

[15 25 35]


In [6]:
#Q4. Add these arrays using broadcasting:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([10, 20, 30])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [10]:
#Q5. Subtract [5, 10, 15] from every row of:
arr = np.array([[20, 30, 40],[50, 60, 70]])
print(arr - np.array([5, 10, 15]))

[[15 20 25]
 [45 50 55]]


In [12]:
#Q21. Increase every student's marks by 5:
marks = np.array([[70, 80, 90],[60, 75, 85],[88, 92, 95]])
print(marks+5)

[[ 75  85  95]
 [ 65  80  90]
 [ 93  97 100]]


In [13]:
#Random Module

In [16]:
#Q1. Generate 5 random numbers between 0 and 1.
import numpy as np
var = np.random.random(5)
print(var)

[0.75863846 0.3375227  0.77755416 0.14581762 0.16036944]


In [18]:
#Q2. Generate 10 random integers between 1 and 100.
var1=np.random.randint(1,101,10)
print(var1)

[44 33 29 37 36 93 98 29 65 77]


In [23]:
#Q3. Generate a 3 × 4 array of random integers between 10 and 50.
arr = np.random.randint(10, 51, (3, 4))
print(arr)

[[22 26 37 35]
 [48 43 21 22]
 [16 39 46 15]]


In [24]:
#Q4. Generate 5 random numbers from a normal distribution.
var = np.random.normal(size=5)
print(var)

[ 0.03420371  0.88865742  0.65890542  0.76853989 -0.9581162 ]


In [27]:
#Q5.Set a random seed and generate 5 random integers. 
#Run the code again and verify that you get the same values.
import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 101, 5)
print(arr)

[52 93 15 72 61]


In [30]:
#Q6. Create an array:[10, 20, 30, 40, 50].Randomly shuffle it.
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[50 40 10 20 30]


In [32]:
#Q7. Randomly select 3 values from:[10, 20, 30, 40, 50, 60, 70]
arr2=np.array([10, 20, 30, 40, 50, 60, 70])
result = np.random.choice(arr2, 3)
print(result)

[20 40 50]
