In [1]:
#Array Manipulation

In [3]:
#Q1. Create a 1D arra of numbers from 1 to 12 and reshape it into a 3x4 array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(arr.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#Q2. Convert a 3 × 4 array into a 2 × 6 array using reshape().
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4))
print(arr.reshape(2,6))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
#Q3. Flatten the following 2D array into a 1D array:

arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [11]:
#Q4. Transpose a 2 × 3 array.
var=np.array([[3,4,5],[6,8,9]])
print(var.transpose())

[[3 4 5]
 [6 8 9]]
[[3 6]
 [4 8]
 [5 9]]


In [13]:
#Q5. Concatenate these two arrays:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concat=np.concatenate((a,b))
print(concat)

[1 2 3 4 5 6]


In [15]:
#Q6. Horizontally stack two 2 × 2 arrays.
arr1=np.array([[4,5],[7,9]])
print(np.hstack(arr1))

[4 5 7 9]


In [16]:
#Q7. Vertically stack two 2 × 2 arrays.
arr2=np.array([[4,5],[7,9]])
print(np.vstack(arr2))

[[4 5]
 [7 9]]


In [17]:
#Q8. Split the array [10,20,30,40,50,60] into 3 equal parts.
var1=np.array([10,20,30,40,50,60])
ar=np.array_split(var1,3)
print(ar)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [18]:
#Axes

In [19]:
#Use:arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [20]:
#Q9. Find the sum of all elements.
print(arr.sum())

450


In [22]:
#Q10. Find the sum of each column using axis.
print(arr.sum(0))

[120 150 180]


In [23]:
#Q11. Find the sum of each row using axis.
print(arr.sum(1))

[ 60 150 240]


In [24]:
#Q12. Find the mean of each column.
print(arr.mean(0))

[40. 50. 60.]


In [25]:
#Q13. Find the maximum value from each row.
print(arr.max(1))

[30 60 90]


In [26]:
#Q14. Find the minimum value from each column.
print(arr.min(0))

[10 20 30]


In [27]:
#Q15. Calculate the standard deviation of each row.
print(arr.std(1))

[8.16496581 8.16496581 8.16496581]
