In [1]:
#Indexing and slicing

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [4]:
#Q1. Print the first element of arr.
print(arr[0])

10


In [5]:
#Q2. Print the last element of arr.
print(arr[6])

70


In [7]:
#Q3. Print the element at index 3.
print(arr[3])

40


In [8]:
#Q4. Print the element at index -2.
print(arr[-2])

60


In [10]:
#Q5. Print the third element using negative indexing.
print(arr[-5])

30


In [12]:
#Q6. Print the first 4 elements.
print(arr[:4])

[10 20 30 40]


In [13]:
#Q7. Print the elements from index 2 to index 5 (excluding index 5).
print(arr[2:5])

[30 40 50]


In [14]:
#Q8. Print the last 3 elements.
print(arr[4:])

[50 60 70]


In [15]:
#Q9. Print every second element
print(arr[::2])

[10 30 50 70]


In [16]:
#Q10. Reverse the entire array using slicing.
print(arr[::-1])

[70 60 50 40 30 20 10]


In [17]:
#Q11. Print the elements from index 1 to the end
print(arr[1:])

[20 30 40 50 60 70]


In [18]:
#Q12. Print the elements from the beginning up to index 4 (excluding 4)
print(arr[:4])

[10 20 30 40]


In [20]:
arr2 = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 100, 110, 120]])
print(arr2)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [21]:
#Q13. Print the element 70.
print(arr2[1,2])

70


In [22]:
#Q14. Print the element 100.
print(arr2[2,1])

100


In [23]:
#Q15. Print the entire first row.
print(arr2[0,0:])

[10 20 30 40]


In [24]:
#Q16. Print the entire last row.
print(arr2[2,0:])

[ 90 100 110 120]


In [26]:
#Q17. Print the second column.
print(arr2[:, 1])

[ 20  60 100]


In [28]:
#Q18. Print the last column.
print(arr2[:, 3])

[ 40  80 120]


In [30]:
#Q19. Print the element at row index 2, column index 1.
print(arr2[2, 1])

100


In [31]:
#Q20. Print the first two rows.
print(arr2[:2])

[[10 20 30 40]
 [50 60 70 80]]


In [32]:
#Using arr2: Q21. Extract the first two rows and first two columns.
print(arr2[:2, :2])

[[10 20]
 [50 60]]


In [33]:
#Q22. Extract the last two rows.
print(arr2[1:, :])

[[ 50  60  70  80]
 [ 90 100 110 120]]


In [34]:
#Q23. Extract the first three columns.
print(arr2[:, :3])

[[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]]


In [35]:
#Q24. Extract the last two columns.
print(arr2[:, 2:])

[[ 30  40]
 [ 70  80]
 [110 120]]


In [36]:
#Q25. Extract:[[60 70] [100 110]]
print(arr2[1:, 1:3])

[[ 60  70]
 [100 110]]


In [37]:
#Q26. Reverse the order of rows.
print(arr2[::-1, :])

[[ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]


In [38]:
#Q27. Reverse the order of columns.
print(arr2[:, ::-1])

[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]]


In [39]:
#Q28. Reverse both rows and columns.
print(arr2[::-1, ::-1])

[[120 110 100  90]
 [ 80  70  60  50]
 [ 40  30  20  10]]
