In [1]:
#Linear Algebra

In [2]:
#Q1. Create two 2 × 2 matrices and calculate their matrix multiplication using @.
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
result = a @ b
print(result)

[[19 22]
 [43 50]]


In [3]:
#Q2. Calculate the dot product of:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)
print(result)

32


In [5]:
#Q3. Find the transpose of:

a=np.array([[1, 2],[3, 4]])
print(np.transpose(a))

[[1 3]
 [2 4]]


In [6]:
#Q4. Find the determinant of:

arr=np.array([[4, 7],[2, 6]])
print(np.linalg.det(arr))

10.000000000000002


In [7]:
#Q5. Find the inverse of:

arr=np.array([[4, 7],[2, 6]])
print(np.linalg.inv(arr))

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [9]:
#Q6. Verify that a matrix multiplied by its inverse gives the identity matrix.
import numpy as np
arr = np.array([[4, 7],[2, 6]])
inverse = np.linalg.inv(arr)
print("Inverse:")
print(inverse)

print("Matrix × Inverse:")
print(arr @ inverse)

Inverse:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Matrix × Inverse:
[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [10]:
#Q7. Find the eigenvalues of:

import numpy as np
arr = np.array([[2, 0],[0, 3]])
eigenvalues = np.linalg.eigvals(arr)
print(eigenvalues)

[2. 3.]


In [11]:
#Q8. Solve the following system of equations using NumPy:
'''2x + y = 5
x + 3y = 6'''

import numpy as np
A = np.array([[2, 1],[1, 3]])
B = np.array([5, 6])
solution = np.linalg.solve(A, B)
print(solution)

[1.8 1.4]
