In [1]:
#NumPy Functions

In [3]:
#Use: marks = np.array([65, 78, 90, 56, 88, 72, 95, 45, 81, 69])

#Q1. Find the total marks.
import numpy as np
marks = np.array([65, 78, 90, 56, 88, 72, 95, 45, 81, 69])
print(marks)
print("Total marks:",np.sum(marks))

[65 78 90 56 88 72 95 45 81 69]
Total marks: 739


In [4]:
#Q2. Find the average marks.
print("Average marks:",np.mean(marks))

Average marks: 73.9


In [5]:
#Q3. Find the median.
print("Median is:", np.median(marks))

Median is: 75.0


In [6]:
#Q4: Find the minimum marks.
print("Minimum marks:", np.min(marks))

Minimum marks: 45


In [7]:
#Q5. Find the maximum marks.
print("Maximum marks:", np.max(marks))

Maximum marks: 95


In [8]:
#Q6. Find the standard deviation.
print("Standard deviation:", np.std(marks))

Standard deviation: 14.942891286494726


In [9]:
#Q7. Find the variance
print("Variance:", np.var(marks))

Variance: 223.29000000000002


In [10]:
#Q8. Round the values to 2 decimal places
arr = np.array([10.234, 20.678, 30.456, 40.999])
print(np.round(arr, 2))

[10.23 20.68 30.46 41.  ]


In [11]:
#Q9: Find the square root of:16, 25, 36, 49, 64
arr=np.array([16, 25, 36, 49, 64])
print(np.sqrt(arr))

[4. 5. 6. 7. 8.]


In [12]:
#Q10 — Find the absolute values of:[-10, 20, -30, 40, -50]

arr = np.array([-10, 20, -30, 40, -50])
print(np.abs(arr))

[10 20 30 40 50]
