Numpy Basics

In [1]:
#Q1. Import NumPy using the standard alias np.
import numpy as np

In [2]:
#Q2. Create a NumPy array containing the numbers 10 to 20
num=np.array([10,11,12,13,14,15,16,17,18,19,20])
print(num)

[10 11 12 13 14 15 16 17 18 19 20]


In [4]:
#Q3. Create an array containing: 5, 10, 15, 20, 25
var=np.array([5,10,15,20,25])
print(var)

[ 5 10 15 20 25]


In [5]:
#Q4. Print the NumPy version installed on your system.
import numpy as np
print(np.__version__)

2.3.5


In [16]:
#Q5. Create an array from the Python list:[12, 25, 7, 18, 30]
numbers=[12,25,7,18,30]
num = np.array(numbers)
print(num)

[12 25  7 18 30]


In [17]:
#Q6. Find the type of the NumPy array created above.
print(type(num))

<class 'numpy.ndarray'>


In [19]:
#Q7. Create an array containing 10 random integers between 1 and 100.
var1=np.random.randint(1,101,10)
print(var1)

[50 28 30 43 54 53 94 23 62 59]


In [20]:
#Q8. Create an array of 10 zeros.
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Creating Arrays

In [25]:
#Q1. Create a 1D array containing numbers from 1 to 10.
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
'''Q2. Create a 2D array:
1  2  3 
4  5  6
7  8  9'''
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
#Q3. Create a 3×3 array filled with zeros.
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#Q4. Create a 4×4 array filled with ones.
ones=np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
#Q5. Create a 3×5 array where every value is 7.
import numpy as np
array = np.full((3, 5), 7)
print(array)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [34]:
#Q6. Create an array containing even numbers from 2 to 20 using arange().
numbers=np.arange(2,21,2)
print(numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [35]:
#Q7. Generate 10 equally spaced numbers between 0 and 1 using linspace().
numbers=np.linspace(0,1,num=10)
print(numbers)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [36]:
#Q8. Create a 5×5 identity matrix.
matrix=np.eye(5,5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
