In [1]:
#Reshaping Arrays

In [2]:
#Q1. Create numbers from 1 to 12 and reshape them into a 3×4 array.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
x=arr.reshape(3,4)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
#Q2. Reshape numbers from 1 to 12 into a 4×3 array.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#Q3. Create numbers from 1 to 20 and reshape them into a 4×5 array.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x=arr.reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
#Q4 — Convert a 2D array into a 1D array using flatten()
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
x = arr.flatten()
print(x)

[1 2 3 4 5 6]


In [7]:
#Q5.Convert a 2D array into a 1D array using ravel().
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
x = arr.ravel()
print(x)

[1 2 3 4 5 6]


In [8]:
'''Q6. Transpose this array:
1 2 3
4 5 6
Expected shape: 3×2'''
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
x = arr.T
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
#Q7. Create a 2×6 array and convert it into a 3×4 array.
import numpy as np
arr = np.arange(1, 13).reshape(2, 6)
print("2×6 array:")
print(arr)

x = arr.reshape(3, 4)
print("3×4 array:")
print(x)

2×6 array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
3×4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#Q8. Take an array of 24 numbers and reshape it into:2×12, 3×8, 4×6, 6×4.
import numpy as np
arr = np.arange(1, 25)
print("2 × 12:")
print(arr.reshape(2, 12))

print("3 × 8:")
print(arr.reshape(3, 8))

print("4 × 6:")
print(arr.reshape(4, 6))

print("6 × 4:")
print(arr.reshape(6, 4))

2 × 12:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
3 × 8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
4 × 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
6 × 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [14]:
#Q9. Check the shape before and after reshaping.
import numpy as np
arr = np.arange(1,13)
print(arr)
print("Before reshaping:", arr.shape)
print()
new_arr = arr.reshape(3,4)
print(new_arr)
print("After reshaping:", new_arr.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
Before reshaping: (12,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After reshaping: (3, 4)
