In [1]:
#Searching, Sorting & Filtering

In [3]:
#Q1. Find all positions where the value 50 occurs:
import numpy as np
arr = np.array([10, 50, 20, 50, 30, 40])
x=np.where(arr==50)
print(x)

(array([1, 3]),)


In [4]:
#Q2. Find all values greater than 50.
arr = np.array([10, 25, 55, 70, 45, 80, 30])
result = arr[arr > 50]
print(result)

[55 70 80]


In [5]:
#Q3. Find all even numbers from:

arr = np.array([11, 24, 37, 42, 55, 68, 71, 80])
even=arr[arr%2==0]
print(even)

[24 42 68 80]


In [8]:
#Q4. Replace all values less than 50 with 0.
arr = np.array([10, 85, 35, 45, 55, 65, 75])
arr[arr < 50] = 0
print(arr)      

[ 0 85  0  0 55 65 75]


In [9]:
#Q5 — Sort the array in ascending order
arr = np.array([45, 12, 89, 34, 67, 23])
print(np.sort(arr))

[12 23 34 45 67 89]


In [10]:
#Q6. Sort the same array in descending order.
arr = np.array([45, 12, 89, 34, 67, 23])
print(np.sort(arr)[::-1])

[89 67 45 34 23 12]


In [11]:
#Q7. Find all unique values:

arr=np.array([10, 20, 10, 30, 20, 40, 30, 30])
x=np.unique(arr)
print(x)

[10 20 30 40]


In [14]:
#Q8. Find the values between 30 and 70 from:

arr = np.array([10, 25, 35, 45, 55, 65, 75, 90])
result = arr[(arr >= 30) & (arr <= 70)]
print(result)

[35 45 55 65]
